<a href="https://colab.research.google.com/github/gilddongddi/Python/blob/main/numpy%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

In [12]:
a = np.arange(15).reshape(3,5)

In [13]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
a.shape

(3, 5)

In [15]:
a.ndim

2

In [16]:
a.dtype.name

'int64'

In [17]:
a.size

15

In [18]:
a.itemsize

8

In [19]:
type(a)

numpy.ndarray

In [20]:
b = np.array([6,7,8])

In [21]:
b

array([6, 7, 8])

In [22]:
type(b)

numpy.ndarray

In [23]:
x = np.array([2,3,4])

In [24]:
x

array([2, 3, 4])

In [25]:
x.dtype

dtype('int64')

In [26]:
y=np.array([1.2,3.5,5.1])

In [27]:
b.dtype

dtype('int64')

In [28]:
a = np.array([1,2,3,4])

In [29]:
b=np.array([(1.5,2,3), (4,5,6)])

In [30]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [31]:
c=np.array([[1.5,2,3],[4,5,6]])

In [32]:
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [33]:
c=np.array([[1,2],[3,4]], dtype=complex)

In [34]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [35]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [37]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [38]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [39]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [40]:
np.empty((4,5))

array([[4.63644338e-310, 5.82997462e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        1.35717430e+131, 9.80546120e-095],
       [9.97664746e+141, 6.01347002e-154, 3.25113981e-086,
        3.25113982e-086, 1.06239598e-153],
       [3.98472821e+252, 1.06244660e-153, 9.78750380e+199,
        6.97843734e+252, 6.80146329e-310]])

In [41]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [42]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [43]:
from numpy import pi

In [44]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [45]:
x=np.linspace(0,2*pi, 100)

In [46]:
f=np.sin(x)

In [47]:
np.linspace(0,2*pi,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [49]:
np.zeros_like((3,4))

array([0, 0])

In [50]:
a = np.arange(6)

In [51]:
print(a)

[0 1 2 3 4 5]


In [52]:
a

array([0, 1, 2, 3, 4, 5])

In [53]:
b=np.arange(12).reshape(4,3)

In [54]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [55]:
c=np.arange(24).reshape(2,3,4)

In [56]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [57]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [58]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [59]:
np.set_printoptions(threshold=sys.maxsize)

NameError: ignored

In [60]:
np.set_printoptions(np.arange(10000))

TypeError: ignored

In [61]:
a = np.array([20,30,40,50])

In [62]:
b=np.arange(4)

In [65]:
b

array([0, 1, 2, 3])

In [66]:
  c=a-b

In [67]:
c

array([20, 29, 38, 47])

In [68]:
b**2

array([0, 1, 4, 9])

In [69]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [70]:
a<35

array([ True,  True, False, False])

In [71]:
A = np.array([[1,1],
              [0,1]])

In [73]:
B = np.array([[2,0],
             [3,4]])

In [74]:
A*B

array([[2, 0],
       [0, 4]])

In [75]:
A@B

array([[5, 4],
       [3, 4]])

In [76]:
A.dig(B)

AttributeError: ignored

In [77]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [78]:
rg = np.random.default_rng(1)

In [79]:
a = np.ones((2,3), dtype=int)

In [80]:
b = rg.random((2,3))

In [81]:
a *=3

In [82]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [83]:
b += a

In [84]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [86]:
a += b

UFuncTypeError: ignored

In [87]:
a = np.ones(3, dtype=np.int32)

In [88]:
b = np.linspace(0,pi,3)

In [89]:
b.dtype.name

'float64'

In [90]:
c = a + b

In [91]:
c

array([1.        , 2.57079633, 4.14159265])

In [92]:
c.dtype.name

'float64'

In [93]:
d = np.exp(c*1j)

In [94]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [95]:
d.dtype.name

'complex128'

In [99]:
a=rg.random((2,3))

In [100]:
a

array([[0.32973172, 0.7884287 , 0.30319483],
       [0.45349789, 0.1340417 , 0.40311299]])

In [101]:
a.sum()

2.412007822394087

In [102]:
a.min()

0.13404169724716475

In [103]:
a.max()

0.7884287034284043

In [104]:
b = np.arange(12).reshape(3,4)

In [105]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [108]:
b.min(axisb=1)

array([0, 4, 8])

In [109]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [110]:
B=np.arange(3)

In [111]:
B

array([0, 1, 2])

In [112]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [113]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [114]:
C = np.array([2.,-1.,4.])

In [115]:
np.add(B,C)

array([2., 0., 6.])

In [116]:
a = np.arange(10)**3

In [117]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [118]:
a[2]

8

In [119]:
a[2:5]

array([ 8, 27, 64])

In [120]:
a[:6:2] = 1000

In [121]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [122]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [125]:
for i in a:
  print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [127]:
def f(x,y):
  return 10*x+y

In [128]:
b = np.fromfunction(f, (5,4), dtype=int)

In [129]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [130]:
b[2,3]

23

In [131]:
b[2]

array([20, 21, 22, 23])

In [132]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [133]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [134]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [135]:
b[-1]

array([40, 41, 42, 43])

In [136]:
c = np.array([[[0,1,2],
               [10,12,13]],
              [[100,101,102],
               [110,112,113]]])

In [137]:
c.shape

(2, 2, 3)

In [138]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [139]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [140]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [141]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
